services:

  siteproxy:
    image: niliaerith/siteproxy
    container_name: siteproxy
    hostname: siteproxy
    restart: always
    ports:
      - 5006:5006
    volumes:
      - /CHANGE_PATH/siteproxy:/home/node/siteproxy
    environment:
      TZ: "Asia/Shanghai"
      PROXY_URL: "http://localhost:5006"
      TOKEN_PREFIX: "/user22334455/"
      LOCAL_LISTEN_PORT: 5006